# <center> Homework 106

In [4]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time

## Task 5

да се тества ползата от transfer learning по отношение на време за обучение при задача 3 от домашно 105

модел B e трениран специално за за binary класификатора и при него нямаме transfer learning

    модела A да се запише след обучението
    да се сравни времето за до-обучение и model_B_on_A спрямо общото време за обучение на модел B
    да се сравни производителността на model_B_on_A спрямо тази на на модел B

In [2]:
fashion_mnist = tf.keras.datasets.fashion_mnist.load_data()
(X_train_full, y_train_full), (X_test, y_test) = fashion_mnist

X_train_full, X_test = X_train_full / 255., X_test / 255.

In [3]:
A_train_mask = (y_train_full != 8) & (y_train_full != 9)
A_test_mask  = (y_test != 8) & (y_test != 9)

B_train_mask = ~A_train_mask
B_test_mask = ~A_test_mask

X_train_full_A, y_train_full_A = X_train_full[A_train_mask], y_train_full[A_train_mask]
X_train_full_B, y_train_full_B = X_train_full[B_train_mask], y_train_full[B_train_mask]
y_train_full_B = (y_train_full_B == 8).astype(int) 

X_test_A, y_test_A = X_test[A_test_mask], y_test[A_test_mask]
X_test_B, y_test_B = X_test[B_test_mask], y_test[B_test_mask]
y_test_B = (y_test_B == 8).astype(int)

X_train_A, y_train_A = X_train_full_A[:-5000], y_train_full_A[:-5000]
X_valid_A, y_valid_A = X_train_full_A[-5000:], y_train_full_A[-5000:]

X_train_B, y_train_B = X_train_full_B[:-5000], y_train_full_B[:-5000]
X_valid_B, y_valid_B = X_train_full_B[-5000:], y_train_full_B[-5000:]

In [5]:
model_A = tf.keras.models.load_model('model_A.keras')
model_A.evaluate(X_test_A, y_test_A)

2026-01-12 16:49:49.533815: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)
2026-01-12 16:49:50.081970: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:84] Allocation of 25088000 exceeds 10% of free system memory.

250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8759 - loss: 0.4018

[0.4018424153327942, 0.8758749961853027]

In [6]:
model_B = tf.keras.models.Sequential(model_A.layers[:-1]) 
model_B.add(tf.keras.layers.Dense(1, activation='sigmoid'))

for layer in model_B.layers[:-1]:
    layer.trainable = False

optimizer = tf.keras.optimizers.SGD(learning_rate=0.001)
model_B.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

start = time.time()
model_B.fit(X_train_B, y_train_B, epochs=5, validation_data=(X_valid_B, y_valid_B))
end = time.time()

transfer_learning_fittime = end - start

for layer in model_B.layers:
    layer.trainable = True

optimizer = tf.keras.optimizers.SGD(learning_rate=0.0001)
model_B.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

start = time.time()
model_B.fit(X_train_B, y_train_B, epochs=15, validation_data=(X_valid_B, y_valid_B))
end = time.time()

transfer_learning_fittime += end - start
_, transfer_learning_test_acc = model_B.evaluate(X_test_B, y_test_B)

print(f'--- Transfer Learning ---\nTotal Fit Time: {transfer_learning_fittime}; Test ACC: {transfer_learning_test_acc}')

Epoch 1/5

2026-01-12 16:56:35.807030: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:84] Allocation of 21952000 exceeds 10% of free system memory.

219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.9507 - loss: 0.1815 - val_accuracy: 0.9706 - val_loss: 0.1136
Epoch 2/5
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9753 - loss: 0.1024 - val_accuracy: 0.9788 - val_loss: 0.0910
Epoch 3/5
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.9806 - loss: 0.0858 - val_accuracy: 0.9820 - val_loss: 0.0792
Epoch 4/5
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.9831 - loss: 0.0762 - val_accuracy: 0.9840 - val_loss: 0.0715
Epoch 5/5
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.9844 - loss: 0.0697 - val_accuracy: 0.9846 - val_loss: 0.0661
Epoch 1/15
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - accuracy: 0.9854 - loss: 0.0664 - val_accuracy: 0.9848 - val_loss: 0.0649
Epoch 2/15
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.9856 - loss: 0.0651 - val_accuracy: 0.9850 - val_loss: 0.0637
Epoch 3/15
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.9860 - loss: 0.0638 - val_accuracy: 0.9852 - val_loss: 0.0625
Epoch 4/15
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.9860 - loss: 0.0627 - val_accuracy: 0.9854 - val_loss: 0.0614
Epoch 5/15
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.9863 - loss: 0.0615 - val_accuracy: 0.9856 - val_loss: 0.0604
Epoch 6/15
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9871 - loss: 0.0605 - val_accuracy: 0.9856 - val_loss: 0.0594
Epoch 7/15
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.9871 - loss: 0.0595 - val_accuracy: 0.9858 - val_loss: 0.0584
Epoch 8/15
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.9874 - loss: 0.0585 - val_accuracy: 0.9864 - val_loss: 0.0575
Epoch 9/15
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 0.9876 - loss: 0.0576 - val_accuracy: 0.9864 - val_loss: 0.0566
Epoch 10/15
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9877 - loss: 0.0567 - val_accuracy: 0.9866 - val_loss: 0.0558
Epoch 11/15
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 0.9880 - loss: 0.0558 - val_accuracy: 0.9866 - val_loss: 0.0550
Epoch 12/15
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.9880 - loss: 0.0550 - val_accuracy: 0.9870 - val_loss: 0.0542
Epoch 13/15
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.9881 - loss: 0.0542 - val_accuracy: 0.9870 - val_loss: 0.0535
Epoch 14/15
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.9881 - loss: 0.0535 - val_accuracy: 0.9872 - val_loss: 0.0527
Epoch 15/15
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.9884 - loss: 0.0527 - val_accuracy: 0.9870 - val_loss: 0.0521
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9875 - loss: 0.0631
--- Transfer Learning ---
Total Fit Time: 58.78576326370239; Test ACC: 0.987500011920929

In [7]:
model_B_without_transf = tf.keras.models.Sequential([
    tf.keras.layers.Input(X_train_B.shape[1:]),
    tf.keras.layers.Flatten(),
    
    tf.keras.layers.Dense(300, activation='relu', kernel_initializer='he_normal'),
    tf.keras.layers.Dense(200, activation='relu', kernel_initializer='he_normal'),
    tf.keras.layers.Dense(100, activation='relu', kernel_initializer='he_normal'),
    tf.keras.layers.Dense(1, activation='sigmoid'),
])

optimizer = tf.keras.optimizers.Adam()
model_B_without_transf.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

start = time.time()
model_B_without_transf.fit(X_train_B, y_train_B, epochs=20, validation_data=(X_valid_B, y_valid_B))
end = time.time()

without_transfer_fittime = end - start
_, without_transfer_test_acc = model_B_without_transf.evaluate(X_test_B, y_test_B)

print(f'--- Without Transfer Learning ---\nFit Time: {without_transfer_fittime}; Test ACC: {without_transfer_test_acc}')

Epoch 1/20

2026-01-12 17:01:26.015317: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:84] Allocation of 21952000 exceeds 10% of free system memory.

219/219 ━━━━━━━━━━━━━━━━━━━━ 7s 20ms/step - accuracy: 0.9923 - loss: 0.0234 - val_accuracy: 0.9972 - val_loss: 0.0093
Epoch 2/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - accuracy: 0.9980 - loss: 0.0061 - val_accuracy: 0.9976 - val_loss: 0.0088
Epoch 3/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - accuracy: 0.9986 - loss: 0.0052 - val_accuracy: 0.9982 - val_loss: 0.0071
Epoch 4/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.9994 - loss: 0.0028 - val_accuracy: 0.9988 - val_loss: 0.0086
Epoch 5/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - accuracy: 0.9980 - loss: 0.0065 - val_accuracy: 0.9988 - val_loss: 0.0054
Epoch 6/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - accuracy: 0.9990 - loss: 0.0031 - val_accuracy: 0.9990 - val_loss: 0.0055
Epoch 7/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 1.0000 - loss: 2.2996e-04 - val_accuracy: 0.9972 - val_loss: 0.0112
Epoch 8/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.9984 - loss: 0.0077 - val_accuracy: 0.9992 - val_loss: 0.0051
Epoch 9/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.9994 - loss: 0.0018 - val_accuracy: 0.9974 - val_loss: 0.0114
Epoch 10/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - accuracy: 0.9993 - loss: 0.0023 - val_accuracy: 0.9990 - val_loss: 0.0043
Epoch 11/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 1.0000 - loss: 6.5555e-05 - val_accuracy: 0.9986 - val_loss: 0.0062
Epoch 12/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - accuracy: 1.0000 - loss: 1.4777e-05 - val_accuracy: 0.9990 - val_loss: 0.0066
Epoch 13/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 1.0000 - loss: 8.4289e-06 - val_accuracy: 0.9990 - val_loss: 0.0071
Epoch 14/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - accuracy: 1.0000 - loss: 5.6193e-06 - val_accuracy: 0.9990 - val_loss: 0.0075
Epoch 15/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - accuracy: 1.0000 - loss: 3.4413e-06 - val_accuracy: 0.9990 - val_loss: 0.0083
Epoch 16/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - accuracy: 1.0000 - loss: 1.9518e-06 - val_accuracy: 0.9990 - val_loss: 0.0088
Epoch 17/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - accuracy: 1.0000 - loss: 1.2745e-06 - val_accuracy: 0.9990 - val_loss: 0.0091
Epoch 18/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - accuracy: 1.0000 - loss: 9.6245e-07 - val_accuracy: 0.9990 - val_loss: 0.0093
Epoch 19/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - accuracy: 1.0000 - loss: 7.9066e-07 - val_accuracy: 0.9990 - val_loss: 0.0095
Epoch 20/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - accuracy: 1.0000 - loss: 6.9387e-07 - val_accuracy: 0.9990 - val_loss: 0.0097
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9975 - loss: 0.0536
--- Without Transfer Learning ---
Fit Time: 76.86660122871399; Test ACC: 0.9975000023841858

In [8]:
task5_res = pd.DataFrame([
    [transfer_learning_fittime / 60, without_transfer_fittime / 60],
    [transfer_learning_test_acc, without_transfer_test_acc]
], ['Fit Time (min)', 'Test ACC'], ['Tranfer', 'Without Tranfer'])

task5_res

                 Tranfer  Without Tranfer
Fit Time (min)  0.979763          1.28111
Test ACC        0.987500          0.99750

## Task 6

да се тества класификатор на fasion MINST със стандартен SGD и със всички други разновидности.

    най добрия модел да се тества със batch normalization
    да се сравнят времената на обучение и производителността на обучените модели

In [11]:
fashion_mnist = tf.keras.datasets.fashion_mnist.load_data()
(X_train_full, y_train_full), (X_test, y_test) = fashion_mnist
X_train, y_train = X_train_full[:-5000], y_train_full[:-5000]
X_valid, y_valid = X_train_full[-5000:], y_train_full[-5000:]

X_train, X_valid, X_test = X_train / 255., X_valid / 255., X_test / 255.

In [10]:
optimizers = {
    'SGD': tf.keras.optimizers.SGD(),
    'SGD_momentum': tf.keras.optimizers.SGD(momentum=0.9),
    'SGD_momentum_nesterov': tf.keras.optimizers.SGD(momentum=0.9, nesterov=True),
    'Adagrad': tf.keras.optimizers.Adagrad(),
    'RMSprop': tf.keras.optimizers.RMSprop(),
    'Adam': tf.keras.optimizers.Adam(),
    'Adamax': tf.keras.optimizers.Adamax(),
    'Nadam': tf.keras.optimizers.Nadam(),
    'AdamW': tf.keras.optimizers.AdamW(),
}

from collections import defaultdict
data = defaultdict(dict)

In [13]:
model_task6 = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=[28, 28]),
    tf.keras.layers.Dense(300, activation="relu", kernel_initializer='he_normal'),
    tf.keras.layers.Dense(100, activation="relu", kernel_initializer='he_normal'),
    tf.keras.layers.Dense(10, activation="softmax")
])

/home/zdravko/Machine_Learning_Intern/venv/lib/python3.13/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [15]:
for name, optimizer in optimizers.items():
    print(f'------- {name} -------')

    model = tf.keras.models.clone_model(model_task6)
    model.compile(optimizer=optimizer, loss="sparse_categorical_crossentropy", metrics=["accuracy"])
    callbacks = [tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)]

    start = time.time()
    history = model.fit(X_train, y_train, epochs=30, 
                        callbacks=callbacks, validation_data=(X_valid, y_valid))
    fit_time = time.time() - start

    test_loss, test_acc = model.evaluate(X_test, y_test)

    data[name]["Epochs"] = len(history.history["loss"])
    data[name]["Best Val Loss"] = min(history.history["val_loss"])
    data[name]["Test Loss"] = test_loss
    data[name]["Test ACC"] = test_acc
    data[name]["Fit Time"] = fit_time

------- SGD -------
Epoch 1/30

2026-01-12 17:55:11.419897: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:84] Allocation of 172480000 exceeds 10% of free system memory.

1719/1719 ━━━━━━━━━━━━━━━━━━━━ 15s 7ms/step - accuracy: 0.7663 - loss: 0.6967 - val_accuracy: 0.8086 - val_loss: 0.5466
Epoch 2/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - accuracy: 0.8339 - loss: 0.4810 - val_accuracy: 0.8378 - val_loss: 0.4652
Epoch 3/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.8474 - loss: 0.4369 - val_accuracy: 0.8498 - val_loss: 0.4235
Epoch 4/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.8576 - loss: 0.4084 - val_accuracy: 0.8604 - val_loss: 0.4069
Epoch 5/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.8645 - loss: 0.3885 - val_accuracy: 0.8558 - val_loss: 0.3977
Epoch 6/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.8690 - loss: 0.3737 - val_accuracy: 0.8624 - val_loss: 0.3886
Epoch 7/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.8742 - loss: 0.3607 - val_accuracy: 0.8642 - val_loss: 0.3673
Epoch 8/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.8793 - loss: 0.3471 - val_accuracy: 0.8708 - val_loss: 0.3594
Epoch 9/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - accuracy: 0.8812 - loss: 0.3375 - val_accuracy: 0.8682 - val_loss: 0.3519
Epoch 10/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.8831 - loss: 0.3289 - val_accuracy: 0.8474 - val_loss: 0.4008
Epoch 11/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.8860 - loss: 0.3199 - val_accuracy: 0.8754 - val_loss: 0.3428
Epoch 12/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - accuracy: 0.8893 - loss: 0.3115 - val_accuracy: 0.8738 - val_loss: 0.3525
Epoch 13/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.8922 - loss: 0.3045 - val_accuracy: 0.8798 - val_loss: 0.3392
Epoch 14/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 14s 8ms/step - accuracy: 0.8942 - loss: 0.2984 - val_accuracy: 0.8766 - val_loss: 0.3428
Epoch 15/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - accuracy: 0.8964 - loss: 0.2921 - val_accuracy: 0.8780 - val_loss: 0.3343
Epoch 16/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - accuracy: 0.8972 - loss: 0.2856 - val_accuracy: 0.8860 - val_loss: 0.3286
Epoch 17/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - accuracy: 0.8993 - loss: 0.2804 - val_accuracy: 0.8820 - val_loss: 0.3357
Epoch 18/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - accuracy: 0.9019 - loss: 0.2750 - val_accuracy: 0.8840 - val_loss: 0.3195
Epoch 19/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - accuracy: 0.9038 - loss: 0.2685 - val_accuracy: 0.8828 - val_loss: 0.3219
Epoch 20/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - accuracy: 0.9053 - loss: 0.2643 - val_accuracy: 0.8836 - val_loss: 0.3199
Epoch 21/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.9064 - loss: 0.2601 - val_accuracy: 0.8828 - val_loss: 0.3214
Epoch 22/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - accuracy: 0.9083 - loss: 0.2545 - val_accuracy: 0.8838 - val_loss: 0.3269
Epoch 23/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - accuracy: 0.9101 - loss: 0.2500 - val_accuracy: 0.8818 - val_loss: 0.3228
 24/313 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8742 - loss: 0.3216

2026-01-12 17:59:28.476613: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:84] Allocation of 31360000 exceeds 10% of free system memory.

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8788 - loss: 0.3423
------- SGD_momentum -------
Epoch 1/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.8124 - loss: 0.5241 - val_accuracy: 0.8528 - val_loss: 0.4059
Epoch 2/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - accuracy: 0.8614 - loss: 0.3824 - val_accuracy: 0.8646 - val_loss: 0.3720
Epoch 3/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 12s 7ms/step - accuracy: 0.8737 - loss: 0.3428 - val_accuracy: 0.8596 - val_loss: 0.3770
Epoch 4/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 15s 8ms/step - accuracy: 0.8824 - loss: 0.3193 - val_accuracy: 0.8698 - val_loss: 0.3572
Epoch 5/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - accuracy: 0.8879 - loss: 0.3001 - val_accuracy: 0.8718 - val_loss: 0.3488
Epoch 6/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.8940 - loss: 0.2853 - val_accuracy: 0.8834 - val_loss: 0.3162
Epoch 7/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 14s 8ms/step - accuracy: 0.8992 - loss: 0.2696 - val_accuracy: 0.8796 - val_loss: 0.3258
Epoch 8/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 14s 8ms/step - accuracy: 0.9025 - loss: 0.2608 - val_accuracy: 0.8774 - val_loss: 0.3365
Epoch 9/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 14s 8ms/step - accuracy: 0.9072 - loss: 0.2485 - val_accuracy: 0.8862 - val_loss: 0.3241
Epoch 10/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - accuracy: 0.9103 - loss: 0.2395 - val_accuracy: 0.8802 - val_loss: 0.3291
Epoch 11/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 14s 8ms/step - accuracy: 0.9134 - loss: 0.2318 - val_accuracy: 0.8834 - val_loss: 0.3331
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8747 - loss: 0.3417
------- SGD_momentum_nesterov -------
Epoch 1/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 17s 9ms/step - accuracy: 0.8246 - loss: 0.4970 - val_accuracy: 0.8568 - val_loss: 0.3874
Epoch 2/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8633 - loss: 0.3746 - val_accuracy: 0.8682 - val_loss: 0.3550
Epoch 3/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8759 - loss: 0.3361 - val_accuracy: 0.8688 - val_loss: 0.3449
Epoch 4/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8838 - loss: 0.3116 - val_accuracy: 0.8754 - val_loss: 0.3361
Epoch 5/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8908 - loss: 0.2957 - val_accuracy: 0.8802 - val_loss: 0.3130
Epoch 6/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8964 - loss: 0.2785 - val_accuracy: 0.8760 - val_loss: 0.3414
Epoch 7/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8999 - loss: 0.2667 - val_accuracy: 0.8730 - val_loss: 0.3487
Epoch 8/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 17s 10ms/step - accuracy: 0.9034 - loss: 0.2559 - val_accuracy: 0.8782 - val_loss: 0.3337
Epoch 9/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.9085 - loss: 0.2446 - val_accuracy: 0.8844 - val_loss: 0.3342
Epoch 10/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.9112 - loss: 0.2384 - val_accuracy: 0.8816 - val_loss: 0.3325
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8749 - loss: 0.3399
------- Adagrad -------
Epoch 1/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 21s 12ms/step - accuracy: 0.6977 - loss: 0.9696 - val_accuracy: 0.7844 - val_loss: 0.6830
Epoch 2/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 17s 10ms/step - accuracy: 0.7942 - loss: 0.6404 - val_accuracy: 0.8110 - val_loss: 0.5841
Epoch 3/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 17s 10ms/step - accuracy: 0.8133 - loss: 0.5706 - val_accuracy: 0.8232 - val_loss: 0.5365
Epoch 4/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8247 - loss: 0.5328 - val_accuracy: 0.8284 - val_loss: 0.5116
Epoch 5/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8310 - loss: 0.5082 - val_accuracy: 0.8312 - val_loss: 0.4913
Epoch 6/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8360 - loss: 0.4906 - val_accuracy: 0.8356 - val_loss: 0.4773
Epoch 7/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8399 - loss: 0.4768 - val_accuracy: 0.8370 - val_loss: 0.4653
Epoch 8/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8429 - loss: 0.4657 - val_accuracy: 0.8386 - val_loss: 0.4594
Epoch 9/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 15s 9ms/step - accuracy: 0.8457 - loss: 0.4564 - val_accuracy: 0.8400 - val_loss: 0.4531
Epoch 10/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8478 - loss: 0.4486 - val_accuracy: 0.8434 - val_loss: 0.4420
Epoch 11/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8498 - loss: 0.4417 - val_accuracy: 0.8428 - val_loss: 0.4372
Epoch 12/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8518 - loss: 0.4357 - val_accuracy: 0.8470 - val_loss: 0.4333
Epoch 13/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8543 - loss: 0.4300 - val_accuracy: 0.8464 - val_loss: 0.4285
Epoch 14/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 15s 9ms/step - accuracy: 0.8559 - loss: 0.4251 - val_accuracy: 0.8470 - val_loss: 0.4239
Epoch 15/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8569 - loss: 0.4207 - val_accuracy: 0.8508 - val_loss: 0.4231
Epoch 16/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8581 - loss: 0.4165 - val_accuracy: 0.8504 - val_loss: 0.4162
Epoch 17/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8593 - loss: 0.4126 - val_accuracy: 0.8512 - val_loss: 0.4143
Epoch 18/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8603 - loss: 0.4089 - val_accuracy: 0.8528 - val_loss: 0.4117
Epoch 19/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8611 - loss: 0.4057 - val_accuracy: 0.8536 - val_loss: 0.4085
Epoch 20/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8621 - loss: 0.4025 - val_accuracy: 0.8548 - val_loss: 0.4052
Epoch 21/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8637 - loss: 0.3997 - val_accuracy: 0.8558 - val_loss: 0.4043
Epoch 22/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8644 - loss: 0.3967 - val_accuracy: 0.8560 - val_loss: 0.4021
Epoch 23/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8648 - loss: 0.3942 - val_accuracy: 0.8580 - val_loss: 0.3993
Epoch 24/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 15s 9ms/step - accuracy: 0.8659 - loss: 0.3916 - val_accuracy: 0.8578 - val_loss: 0.3975
Epoch 25/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8665 - loss: 0.3893 - val_accuracy: 0.8604 - val_loss: 0.3954
Epoch 26/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8669 - loss: 0.3872 - val_accuracy: 0.8604 - val_loss: 0.3939
Epoch 27/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8681 - loss: 0.3850 - val_accuracy: 0.8612 - val_loss: 0.3926
Epoch 28/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8685 - loss: 0.3829 - val_accuracy: 0.8610 - val_loss: 0.3924
Epoch 29/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8691 - loss: 0.3807 - val_accuracy: 0.8618 - val_loss: 0.3898
Epoch 30/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.8691 - loss: 0.3791 - val_accuracy: 0.8630 - val_loss: 0.3866
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8520 - loss: 0.4182
------- RMSprop -------
Epoch 1/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 21s 11ms/step - accuracy: 0.8184 - loss: 0.5039 - val_accuracy: 0.8338 - val_loss: 0.4784
Epoch 2/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 19s 11ms/step - accuracy: 0.8640 - loss: 0.3802 - val_accuracy: 0.8362 - val_loss: 0.4670
Epoch 3/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 20s 12ms/step - accuracy: 0.8738 - loss: 0.3567 - val_accuracy: 0.8750 - val_loss: 0.3712
Epoch 4/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 20s 12ms/step - accuracy: 0.8788 - loss: 0.3442 - val_accuracy: 0.8544 - val_loss: 0.4301
Epoch 5/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 23s 13ms/step - accuracy: 0.8828 - loss: 0.3362 - val_accuracy: 0.8752 - val_loss: 0.3723
Epoch 6/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 22s 13ms/step - accuracy: 0.8861 - loss: 0.3274 - val_accuracy: 0.8606 - val_loss: 0.4732
Epoch 7/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 22s 13ms/step - accuracy: 0.8877 - loss: 0.3205 - val_accuracy: 0.8610 - val_loss: 0.4441
Epoch 8/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 23s 13ms/step - accuracy: 0.8911 - loss: 0.3192 - val_accuracy: 0.8770 - val_loss: 0.4273
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8643 - loss: 0.3962
------- Adam -------
Epoch 1/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 27s 15ms/step - accuracy: 0.8259 - loss: 0.4841 - val_accuracy: 0.8562 - val_loss: 0.3832
Epoch 2/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 24s 14ms/step - accuracy: 0.8658 - loss: 0.3644 - val_accuracy: 0.8700 - val_loss: 0.3558
Epoch 3/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 25s 15ms/step - accuracy: 0.8787 - loss: 0.3253 - val_accuracy: 0.8704 - val_loss: 0.3524
Epoch 4/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 41s 15ms/step - accuracy: 0.8866 - loss: 0.3038 - val_accuracy: 0.8728 - val_loss: 0.3421
Epoch 5/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 25s 15ms/step - accuracy: 0.8939 - loss: 0.2868 - val_accuracy: 0.8750 - val_loss: 0.3346
Epoch 6/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 25s 15ms/step - accuracy: 0.8983 - loss: 0.2706 - val_accuracy: 0.8854 - val_loss: 0.3206
Epoch 7/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 25s 15ms/step - accuracy: 0.9031 - loss: 0.2550 - val_accuracy: 0.8818 - val_loss: 0.3177
Epoch 8/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 25s 14ms/step - accuracy: 0.9079 - loss: 0.2448 - val_accuracy: 0.8854 - val_loss: 0.3355
Epoch 9/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 26s 15ms/step - accuracy: 0.9113 - loss: 0.2356 - val_accuracy: 0.8812 - val_loss: 0.3235
Epoch 10/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 25s 14ms/step - accuracy: 0.9150 - loss: 0.2254 - val_accuracy: 0.8846 - val_loss: 0.3355
Epoch 11/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 42s 15ms/step - accuracy: 0.9184 - loss: 0.2150 - val_accuracy: 0.8892 - val_loss: 0.3443
Epoch 12/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 25s 15ms/step - accuracy: 0.9198 - loss: 0.2076 - val_accuracy: 0.8918 - val_loss: 0.3354
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8810 - loss: 0.3435
------- Adamax -------
Epoch 1/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 26s 14ms/step - accuracy: 0.8242 - loss: 0.5108 - val_accuracy: 0.8458 - val_loss: 0.4427
Epoch 2/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 25s 14ms/step - accuracy: 0.8644 - loss: 0.3844 - val_accuracy: 0.8630 - val_loss: 0.3824
Epoch 3/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 24s 14ms/step - accuracy: 0.8772 - loss: 0.3437 - val_accuracy: 0.8722 - val_loss: 0.3513
Epoch 4/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 25s 14ms/step - accuracy: 0.8852 - loss: 0.3189 - val_accuracy: 0.8668 - val_loss: 0.3518
Epoch 5/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 23s 14ms/step - accuracy: 0.8917 - loss: 0.2974 - val_accuracy: 0.8808 - val_loss: 0.3302
Epoch 6/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 24s 14ms/step - accuracy: 0.8973 - loss: 0.2829 - val_accuracy: 0.8798 - val_loss: 0.3275
Epoch 7/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 40s 14ms/step - accuracy: 0.9016 - loss: 0.2683 - val_accuracy: 0.8792 - val_loss: 0.3331
Epoch 8/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 24s 14ms/step - accuracy: 0.9063 - loss: 0.2567 - val_accuracy: 0.8848 - val_loss: 0.3108
Epoch 9/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 25s 14ms/step - accuracy: 0.9094 - loss: 0.2465 - val_accuracy: 0.8924 - val_loss: 0.3052
Epoch 10/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 23s 13ms/step - accuracy: 0.9136 - loss: 0.2359 - val_accuracy: 0.8812 - val_loss: 0.3350
Epoch 11/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 23s 14ms/step - accuracy: 0.9162 - loss: 0.2285 - val_accuracy: 0.8872 - val_loss: 0.3108
Epoch 12/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 23s 13ms/step - accuracy: 0.9189 - loss: 0.2183 - val_accuracy: 0.8858 - val_loss: 0.3143
Epoch 13/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 41s 14ms/step - accuracy: 0.9226 - loss: 0.2100 - val_accuracy: 0.8918 - val_loss: 0.3006
Epoch 14/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 22s 13ms/step - accuracy: 0.9246 - loss: 0.2043 - val_accuracy: 0.8910 - val_loss: 0.3128
Epoch 15/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 25s 15ms/step - accuracy: 0.9274 - loss: 0.1960 - val_accuracy: 0.8914 - val_loss: 0.3081
Epoch 16/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 23s 14ms/step - accuracy: 0.9300 - loss: 0.1889 - val_accuracy: 0.8886 - val_loss: 0.3217
Epoch 17/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 23s 14ms/step - accuracy: 0.9318 - loss: 0.1833 - val_accuracy: 0.8840 - val_loss: 0.3378
Epoch 18/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 23s 14ms/step - accuracy: 0.9349 - loss: 0.1757 - val_accuracy: 0.8950 - val_loss: 0.3018
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8903 - loss: 0.3191
------- Nadam -------
Epoch 1/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 29s 16ms/step - accuracy: 0.8342 - loss: 0.4658 - val_accuracy: 0.8690 - val_loss: 0.3685
Epoch 2/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 28s 16ms/step - accuracy: 0.8699 - loss: 0.3539 - val_accuracy: 0.8744 - val_loss: 0.3504
Epoch 3/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 28s 16ms/step - accuracy: 0.8823 - loss: 0.3198 - val_accuracy: 0.8796 - val_loss: 0.3248
Epoch 4/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 27s 16ms/step - accuracy: 0.8895 - loss: 0.2957 - val_accuracy: 0.8834 - val_loss: 0.3390
Epoch 5/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 27s 16ms/step - accuracy: 0.8969 - loss: 0.2776 - val_accuracy: 0.8778 - val_loss: 0.3315
Epoch 6/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 28s 17ms/step - accuracy: 0.9017 - loss: 0.2618 - val_accuracy: 0.8824 - val_loss: 0.3272
Epoch 7/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 28s 16ms/step - accuracy: 0.9060 - loss: 0.2513 - val_accuracy: 0.8874 - val_loss: 0.3223
Epoch 8/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 28s 16ms/step - accuracy: 0.9106 - loss: 0.2385 - val_accuracy: 0.8778 - val_loss: 0.3328
Epoch 9/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 28s 16ms/step - accuracy: 0.9127 - loss: 0.2296 - val_accuracy: 0.8870 - val_loss: 0.3294
Epoch 10/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 28s 16ms/step - accuracy: 0.9179 - loss: 0.2187 - val_accuracy: 0.8756 - val_loss: 0.3547
Epoch 11/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 27s 16ms/step - accuracy: 0.9194 - loss: 0.2118 - val_accuracy: 0.8858 - val_loss: 0.3278
Epoch 12/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 27s 16ms/step - accuracy: 0.9226 - loss: 0.2030 - val_accuracy: 0.8850 - val_loss: 0.3375
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8862 - loss: 0.3355
------- AdamW -------
Epoch 1/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 27s 15ms/step - accuracy: 0.8278 - loss: 0.4818 - val_accuracy: 0.8560 - val_loss: 0.3823
Epoch 2/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 25s 14ms/step - accuracy: 0.8653 - loss: 0.3647 - val_accuracy: 0.8684 - val_loss: 0.3468
Epoch 3/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 25s 14ms/step - accuracy: 0.8782 - loss: 0.3265 - val_accuracy: 0.8746 - val_loss: 0.3425
Epoch 4/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 25s 15ms/step - accuracy: 0.8871 - loss: 0.3030 - val_accuracy: 0.8736 - val_loss: 0.3460
Epoch 5/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 24s 14ms/step - accuracy: 0.8957 - loss: 0.2836 - val_accuracy: 0.8800 - val_loss: 0.3229
Epoch 6/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 24s 14ms/step - accuracy: 0.8984 - loss: 0.2720 - val_accuracy: 0.8732 - val_loss: 0.3557
Epoch 7/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 42s 15ms/step - accuracy: 0.9037 - loss: 0.2586 - val_accuracy: 0.8826 - val_loss: 0.3265
Epoch 8/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 25s 14ms/step - accuracy: 0.9077 - loss: 0.2471 - val_accuracy: 0.8874 - val_loss: 0.3318
Epoch 9/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 25s 14ms/step - accuracy: 0.9095 - loss: 0.2377 - val_accuracy: 0.8812 - val_loss: 0.3376
Epoch 10/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 25s 14ms/step - accuracy: 0.9135 - loss: 0.2292 - val_accuracy: 0.8820 - val_loss: 0.3339
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8772 - loss: 0.3448

In [22]:
res_task6 = pd.DataFrame(data)
res_task6.loc['Fit Time (min)'] = res_task6.loc['Fit Time'] / 60
res_task6.drop(index='Fit Time', inplace=True)
res_task6.T.sort_values('Test ACC', ascending=False)

,Epochs,Best Val Loss,Test Loss,Test ACC,Fit Time (min)
Adamax,18.0,0.300604,0.319125,0.8903,7.733704
Nadam,12.0,0.322348,0.335495,0.8862,5.569909
Adam,12.0,0.317705,0.343454,0.8810,5.597603
SGD,23.0,0.319490,0.342346,0.8788,4.293710
AdamW,10.0,0.322893,0.344814,0.8772,4.452555
SGD_momentum_nesterov,10.0,0.312984,0.339943,0.8749,2.692260
SGD_momentum,11.0,0.316192,0.341728,0.8747,2.473622
RMSprop,8.0,0.371220,0.396185,0.8643,2.854045
Adagrad,30.0,0.386580,0.418235,0.8520,8.061788

In [25]:
best_model_task6 = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=[28, 28]),

    tf.keras.layers.Dense(300, kernel_initializer='he_normal'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.ReLU(),

    tf.keras.layers.Dense(100, kernel_initializer='he_normal'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.ReLU(),

    tf.keras.layers.Dense(10, activation="softmax")
])

best_model_task6.compile(optimizer=tf.keras.optimizers.Adamax(), 
                         loss="sparse_categorical_crossentropy", metrics=["accuracy"])
callbacks = [tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)]

start = time.time()
history = best_model_task6.fit(X_train, y_train, epochs=30, 
                    callbacks=callbacks, validation_data=(X_valid, y_valid))
fit_time = time.time() - start

test_loss, test_acc = best_model_task6.evaluate(X_test, y_test)

print(f'--- Best Model Optimizer: Adamax ---\nFit Time: {fit_time / 60}; Test ACC: {test_acc}; Test Loss: {test_loss}')

Epoch 1/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 23s 12ms/step - accuracy: 0.8338 - loss: 0.4826 - val_accuracy: 0.8696 - val_loss: 0.3684
Epoch 2/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 20s 11ms/step - accuracy: 0.8729 - loss: 0.3544 - val_accuracy: 0.8708 - val_loss: 0.3586
Epoch 3/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 20s 11ms/step - accuracy: 0.8876 - loss: 0.3112 - val_accuracy: 0.8824 - val_loss: 0.3215
Epoch 4/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 20s 12ms/step - accuracy: 0.8971 - loss: 0.2823 - val_accuracy: 0.8834 - val_loss: 0.3167
Epoch 5/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 20s 11ms/step - accuracy: 0.9062 - loss: 0.2611 - val_accuracy: 0.8782 - val_loss: 0.3355
Epoch 6/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 20s 11ms/step - accuracy: 0.9099 - loss: 0.2450 - val_accuracy: 0.8812 - val_loss: 0.3247
Epoch 7/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 21s 12ms/step - accuracy: 0.9152 - loss: 0.2298 - val_accuracy: 0.8730 - val_loss: 0.3363
Epoch 8/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 21s 12ms/step - accuracy: 0.9211 - loss: 0.2145 - val_accuracy: 0.8846 - val_loss: 0.3102
Epoch 9/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 22s 13ms/step - accuracy: 0.9255 - loss: 0.2025 - val_accuracy: 0.8872 - val_loss: 0.3180
Epoch 10/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 39s 12ms/step - accuracy: 0.9304 - loss: 0.1907 - val_accuracy: 0.8890 - val_loss: 0.3172
Epoch 11/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 21s 12ms/step - accuracy: 0.9335 - loss: 0.1820 - val_accuracy: 0.8808 - val_loss: 0.3275
Epoch 12/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 20s 12ms/step - accuracy: 0.9378 - loss: 0.1716 - val_accuracy: 0.8760 - val_loss: 0.3540
Epoch 13/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 22s 13ms/step - accuracy: 0.9414 - loss: 0.1628 - val_accuracy: 0.8832 - val_loss: 0.3446
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8789 - loss: 0.3400
--- Best Model Optimizer: Adamax ---
Fit Time: 4.833022288481394; Test ACC: 0.8788999915122986; Test Loss: 0.3400341868400574